name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # execute everday
  workflow_dispatch:    # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/src/svg/github-contribution-grid-snake.svg
            dist/src/svg/github-contribution-grid-snake.gif

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
